ANYbotics/grid_map

- grid_map_core/CMakeLists.txt
- grid_map_core/include/grid_map_core/Polygon.hpp
- grid_map_core/include/grid_map_core/TypeDefs.hpp
- grid_map_core/include/grid_map_eigen_plugins/DenseBasePlugin.hpp
- grid_map_core/include/grid_map_eigen_plugins/FunctorsPlugin.hpp
- grid_map_core/src/Polygon.cpp
- grid_map_core/test/EigenPluginsTest.cpp
We can now do things like:
```C++
Eigen::Matrix<double, 7, 18> matrix;
matrix.numberOfFinites();
matrix.sumOfFinites();
matrix.meanOfFinites();
```
Do we need anything else?
> Added Eigen plugins for handling of matrices with Nan values.

- grid_map_demos/CMakeLists.txt
Demo image launcher failing without this.
> Install the image publisher script into the runtime directory

- README.md
- grid_map/CHANGELOG.rst
- grid_map_core/CHANGELOG.rst
- grid_map_demos/CHANGELOG.rst
- grid_map_demos/config/image_to_gridmap_demo.yaml
- grid_map_demos/src/ImageToGridmapDemo.cpp
- grid_map_filters/CHANGELOG.rst
- grid_map_loader/CHANGELOG.rst
- grid_map_msgs/CHANGELOG.rst
- grid_map_ros/CHANGELOG.rst
- grid_map_ros/include/grid_map_ros/GridMapRosConverter.hpp
- grid_map_ros/src/GridMapRosConverter.cpp
- grid_map_visualization/CHANGELOG.rst
- grid_map_visualization/CMakeLists.txt
- grid_map_visualization/include/grid_map_visualization/visualizations/FlatPointCloudVisualization.hpp
- grid_map_visualization/include/grid_map_visualization/visualizations/PointCloudVisualization.hpp
- grid_map_visualization/include/grid_map_visualization/visualizations/VisualizationBase.hpp
- grid_map_visualization/src/visualizations/FlatPointCloudVisualization.cpp
- grid_map_visualization/src/visualizations/PointCloudVisualization.cpp
- grid_map_visualization/src/visualizations/VisualizationBase.cpp
- grid_map_visualization/src/visualizations/VisualizationFactory.cpp
> Flat point clouds

- grid_map_core/include/grid_map_core/Polygon.hpp
- grid_map_core/include/grid_map_core/iterators/CircleIterator.hpp
- grid_map_core/include/grid_map_core/iterators/EllipseIterator.hpp
- grid_map_core/include/grid_map_core/iterators/PolygonIterator.hpp
- grid_map_core/include/grid_map_core/iterators/SpiralIterator.hpp
- grid_map_core/src/Polygon.cpp
- grid_map_core/src/iterators/CircleIterator.cpp
- grid_map_core/src/iterators/EllipseIterator.cpp
- grid_map_core/src/iterators/PolygonIterator.cpp
- grid_map_core/src/iterators/SpiralIterator.cpp
So it can be used in const functions.
> Makes the isInside checks const

- grid_map_core/src/GridMap.cpp
Hello,
I have been using the interpolated version of atPosition and I noted (using gperftools) that in my code, 40% of the CPU time is spent in this function. So I re-implemented the interpolation in a more efficient way (it is basically reducing the coordinates to 4 points of coordinates (0,0), (1,0), (0,1),(1,1) ). Now atPosition uses 8% of CPU time in my application.
> re-implemented interpolation methods more efficiently

- grid_map_core/include/grid_map_core/GridMap.hpp
> fixed eigen alignment in GridMap class

- grid_map_core/src/Polygon.cpp
- grid_map_core/test/PolygonTest.cpp
> Capture case when both circles are the same in convexHullOfTwoCircles.

- grid_map_core/include/grid_map_core/Polygon.hpp
- grid_map_core/src/Polygon.cpp
Fixed some warnings that would be triggered in downstream packages including header files from this repo when building with the '-Wall -Wextra -Wpedantic' compiler flags.
> Fixed some compiler warnings.

- grid_map_core/CMakeLists.txt
- grid_map_cv/CMakeLists.txt
- grid_map_cv/filter_plugins.xml
- grid_map_cv/include/grid_map_cv/GridMapCvConverter.hpp
- grid_map_cv/include/grid_map_cv/GridMapCvProcessing.hpp
- grid_map_cv/include/grid_map_cv/InpaintFilter.hpp
- grid_map_cv/include/grid_map_cv/grid_map_cv.hpp
- grid_map_cv/package.xml
- grid_map_cv/src/GridMapCvProcessing.cpp
- grid_map_cv/src/InpaintFilter.cpp
- grid_map_cv/test/GridMapCvProcessingTest.cpp
- grid_map_cv/test/GridMapCvTest.cpp
- grid_map_cv/test/test_grid_map_cv.cpp
related to #219.
grid_map_cv package linted and ported.
This PR also includes a fix to grid_map_core/CMakeLists.txt which could be found in 48c72e0. This fix is addressing the omission of an extra cmake config file and the omission of exporting the include directories.
re-submission to trigger CI #238.
> [ROS2] grid_map_cv port (re-submission) (new branch)

- .circleci/config.yml
- grid_map_costmap_2d/test/test_costmap_2d_ros.cpp
- grid_map_octomap/CMakeLists.txt
- grid_map_octomap/include/grid_map_octomap/GridMapOctomapConverter.hpp
- grid_map_octomap/include/grid_map_octomap/grid_map_octomap.hpp
- grid_map_octomap/package.xml
- grid_map_octomap/src/GridMapOctomapConverter.cpp
- grid_map_octomap/test/OctomapConverterTest.cpp
- grid_map_octomap/test/test_grid_map_octomap.cpp
- tools/ros2_dependencies.repos
* Linted files
* Updated package.xml & CMakeLists.txt
* Added ocotmap as a dependency to ros2_dependencies.repos
> [ros2] grid_map_octomap port

- grid_map_loader/CMakeLists.txt
- grid_map_loader/include/grid_map_loader/GridMapLoader.hpp
- grid_map_loader/package.xml
- grid_map_loader/src/GridMapLoader.cpp
- grid_map_loader/src/grid_map_loader_node.cpp
- grid_map_ros/include/grid_map_ros/GridMapRosConverter.hpp
- grid_map_ros/include/grid_map_ros/message_traits.hpp
- grid_map_ros/src/GridMapRosConverter.cpp
- grid_map_ros/test/GridMapRosTest.cpp
- Linted
- ROS related APIs updated
> [ROS2] grid_map_loader port

- grid_map_rviz_plugin/CMakeLists.txt
- grid_map_sdf/src/SignedDistanceField.cpp
Merging fixes from master into melodic-devel branch.
> Update PR from master into melodic-devel

- grid_map_pcl/CHANGELOG.rst
- grid_map_pcl/CMakeLists.txt
- grid_map_pcl/package.xml
* Replaced pcl_ros dependency with PCL
* Updated changelog
> Replaced pcl_ros dependency with PCL for grid_map_pcl (branch: foxy-devel)

- grid_map_pcl/CHANGELOG.rst
- grid_map_pcl/CMakeLists.txt
- grid_map_pcl/package.xml
* Replaced pcl_ros dependency with PCL
* Updated changelog
> Replaced pcl_ros dependency with PCL for grid_map_pcl (branch: ros2)

- grid_map_costmap_2d/package.xml
- grid_map_cv/package.xml
- grid_map_pcl/package.xml
- Updated grid_map_costmap_2d/package.xml version to match remaining packages.
- Added explicit dependency ament_cmake_gtest to grid_map_cv/package.xml for its unit tests
Cheers
> package.xml update

- .circleci/config.yml
- grid_map_core/include/grid_map_core/BufferRegion.hpp
- grid_map_core/include/grid_map_core/Polygon.hpp
- grid_map_core/include/grid_map_core/gtest_eigen.hpp
- grid_map_core/src/BufferRegion.cpp
- grid_map_core/src/Polygon.cpp
- grid_map_demos/CMakeLists.txt
- grid_map_demos/include/grid_map_demos/ImageToGridmapDemo.hpp
- grid_map_filters/CMakeLists.txt
- grid_map_pcl/src/GridMapPclLoader.cpp
- grid_map_ros/src/GridMapRosConverter.cpp
- tools/ros2_dependencies.repos
https://github.com/ANYbotics/grid_map/pull/318 + Fix circleci.
> Fix for clang build and circleci

- grid_map_pcl/src/GridMapPclLoader.cpp
- grid_map_pcl/test/test_data/parameters.yaml
Some test in grid map pcl are failed because of the changes in #323.
I modified those tests in this PR.
> ci: fix tests in grid map pcl

- grid_map_cv/include/grid_map_cv/utilities.hpp
- grid_map_demos/package.xml
- add execution dependencies
- update declare parameter api
> fix: make demos work

- README.md
Fixed README so it has the correct ros version and branches
> Update README.md branches for humble

- grid_map/CMakeLists.txt
- grid_map_cmake_helpers/cmake/grid_map_package.cmake
Set minimum language requirements consistently in the repo, and remove incorrect comments.
> Enfore C++17

- README.md
Forward port of https://github.com/ANYbotics/grid_map/pull/408 to Iron. 
@Claudio-Chies Can I get an approval?
> Fix name for Iron

- grid_map_rviz_plugin/src/GridMapVisual.cpp
> update deprecated ogre header file

- .github/workflows/colcon.yaml
- tools/ros2_dependencies.repos
- update build actions for ros2 rolling
> ci: update rolling ci

- .github/.mergify.yml
Add  a mergify action such that we can backport to Jazzy
> Add ROS 2 Jazzy backport mergify rule

- .github/workflows/colcon.yaml
- try to fix https://github.com/ANYbotics/grid_map/pull/470#issuecomment-2256179459
> ci: import src only when rosdistro is rolling
