grid_map_msgs/CMakeLists.txt, grid_map_msgs/package.xml
So users of `grid_map_msgs` can depend on them.
=> Package exports for grid map messages

grid_map_core/include/grid_map_core/GridMap.hpp, grid_map_core/src/GridMap.cpp
So we can use it when grid maps are passed in as const references to functions.
=> Const correctness for getSubmap

grid_map_core/src/GridMapMath.cpp, grid_map_core/test/GridMapMathTest.cpp
In my first commit I added a test case that tests the return value of `getIndexFromPosition()` when a position right on the edge is given. Turns out that the function returns `true` and the returned index is invalid (index is equal to bufferSize). I noticed that `checkIfPositionWithinMap()` accepts positions that are exactly on the edge of the map but when the index is generated there is no check to validate that the index is still in range.
My solution was to modify `checkIfPositionWithinMap()` and not accept positions on the edge of the map. It seems that this change doesn't affect anything else.
Another solution (if it is desired to accept edge positions) would be to make sure that the returned index will be in-bounds, in similar fashion as the `limitPositionToRange()` does. In this …
=> getIndexFromPosition() should not return index larger than bufferSize

grid_map_ros/include/grid_map_ros/GridMapRosConverter.hpp, grid_map_ros/src/GridMapRosConverter.cpp, grid_map_visualization/include/grid_map_visualization/visualizations/PointCloudVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/VisualizationBase.hpp, grid_map_visualization/src/visualizations/PointCloudVisualization.cpp, grid_map_visualization/src/visualizations/VisualizationBase.cpp
For double maps, converting to an occupancy grid map is a right nuisance inasmuch as you have to take care to convert values within 'proper' cost value bounds.
This PR provides a way to construct a 'flat' point cloud, that will the subsequently show the values in the layer via the colour derived from the grid map values stored in a channel.
Example yaml for the visualization node:
```
grid_map_topic: /planner/potential_grid_map
grid_map_visualizations:
- name: potentials
type: point_cloud
params:
layer: normalised
flat: true
```
Some points to note:
* This changes the `toPointCloud` api, could drop the boolean down and give it a default argument, but that would alter the style of the rest of the functions for which `const` args always precede.
* Should the visualisation dump *all* other …
=> Visualise flat point clouds

grid_map_cv/include/grid_map_cv/GridMapCvConverter.hpp
Having only the declarations yields to undefined references, so I removed them.
=> Fix/Remove constructor and destructor declaration in GridMapCvConverter

grid_map_pcl/src/GridMapPclConverter.cpp
As above. This is a small change but gives a big difference in the output map in some cases. This is particularly true in the case that mesh triangles happen to be generated on the same grid as the grid map, and the number of glancing ray casts is large. See the example below where the mesh was generated by voxblox.
Before:
After:
=> Added comparison delta to ray tracing to make glancing intersection hits

grid_map_ros/CMakeLists.txt, grid_map_ros/include/grid_map_ros/Costmap2DConverter.hpp, grid_map_ros/package.xml
Added backwards compatibility for costmap_2d conversion in grid_map_ros and marked it as deprecated.
=> Fixing cost_map regression

grid_map_core/CMakeLists.txt, grid_map_core/src/GridMapMath.cpp, grid_map_core/src/iterators/SpiralIterator.cpp, grid_map_core/test/SpiralIteratorTest.cpp
In case the center of the `SpiralIterator` happens to be outside the map
a segmentation fault occurs when trying to use the iterator.
In this case the index of the center was not computed,
because `getIndexFromPosition` returned false without changing
the value of the index. With this patch, the index is computed, but the function still
returns false when the position is outside the map.
Additionally, only the cells adjacent to the center were looked at in that case.
When these cells are outside the map too, dereferencing the pointer leads
to a segmentation fault. This was fixed by generating rings until a position inside the map is reached.
=> Fix segfault in SpiralIterator the center is outside the map

grid_map_cv/include/grid_map_cv/GridMapCvConverter.hpp
Bug has been noticed after converting a grid map and clamping the ray count to a reasonable number.
Converting the non clamped values produces the invalid picture.
=> Fixed: Clamp changes were disregarded

grid_map_core/src/Polygon.cpp
I found this potential issue while debugging [https://github.com/leggedrobotics/free_gait/pull/39](url).
This is only a suggestion and not needed to solve the free gait visualization issue.
=> grid_map_core: Polygon triangulation checks number of vertices.

grid_map_cv/CMakeLists.txt, grid_map_demos/CMakeLists.txt, grid_map_ros/src/GridMapRosConverter.cpp
Previously all needed components were included by cv_bridge, but now cv_bridge does not include all opencv components, so they need to be explicitly added in other packages.
Specifically, about 3 months ago cv_bridge was updated to use
```
find_package(OpenCV 3 REQUIRED
COMPONENTS
opencv_core
opencv_imgproc
opencv_imgcodecs
CONFIG
)
```
instead of 
`find_package(OpenCV REQUIRED)`
https://github.com/ros-perception/vision_opencv/commit/8b5bbcbc1ce65734dc600695487909e0c67c1033
Previously, all of the components of OpenCV were included in the dependent libraries because of this; however, now only the listed libraries are there. So master failed to compile because the highgui library is not included. Doing another find_package in the dependent libraries lets you add in the missing (highgui) …
=> Adds in dependencies on OpenCV. 

grid_map_demos/CMakeLists.txt
Removes the components part of the grid_map_demos opencv find_package call
=> Possible master compilation fix (OpenCV lib issue)

grid_map_msgs/srv/ProcessFile.srv
Functions [`saveToBag`](https://github.com/ANYbotics/grid_map/blob/master/grid_map_ros/include/grid_map_ros/GridMapRosConverter.hpp#L237) and [`loadFromBag`](https://github.com/ANYbotics/grid_map/blob/master/grid_map_ros/include/grid_map_ros/GridMapRosConverter.hpp#L247) from "GridMapRosConverter.hpp" require an absolute path of the rosbg and a topic name.
Service ['ProcessFile.srv'](https://github.com/ANYbotics/grid_map/blob/master/grid_map_msgs/srv/ProcessFile.srv) is extended to allow the specification of a topic name.
=> Extend ProcessFile.srv to include topic_name field.

grid_map_core/include/grid_map_core/Polygon.hpp, grid_map_core/src/Polygon.cpp, grid_map_filters/src/MinInRadiusFilter.cpp, grid_map_ros/include/grid_map_ros/GridMapMsgHelpers.hpp, grid_map_ros/src/GridMapMsgHelpers.cpp
Resolve for ignored qualifiers that appear when built with `-Wignored-qualifiers` option
=> Resolve ignored qualifiers

.circleci/config.yml, grid_map_visualization/CMakeLists.txt, grid_map_visualization/include/grid_map_visualization/GridMapVisualization.hpp, grid_map_visualization/include/grid_map_visualization/GridMapVisualizationHelpers.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/FlatPointCloudVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/GridCellsVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/MapRegionVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/OccupancyGridVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/PointCloudVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/VectorVisualization.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/VisualizationBase.hpp, grid_map_visualization/include/grid_map_visualization/visualizations/VisualizationFactory.hpp, grid_map_visualization/package.xml, grid_map_visualization/src/GridMapVisualization.cpp, grid_map_visualization/src/GridMapVisualizationHelpers.cpp, grid_map_visualization/src/grid_map_visualization_node.cpp, grid_map_visualization/src/visualizations/FlatPointCloudVisualization.cpp, grid_map_visualization/src/visualizations/GridCellsVisualization.cpp, grid_map_visualization/src/visualizations/MapRegionVisualization.cpp, grid_map_visualization/src/visualizations/OccupancyGridVisualization.cpp, grid_map_visualization/src/visualizations/PointCloudVisualization.cpp, grid_map_visualization/src/visualizations/VectorVisualization.cpp, grid_map_visualization/src/visualizations/VisualizationBase.cpp, grid_map_visualization/src/visualizations/VisualizationFactory.cpp, tools/ros2_dependencies.repos
Changes:
- Unsubscribing from topics is not available atm in rclcpp (according to [this](https://answers.ros.org/question/354792/rclcpp-how-to-unsubscribe-from-a-topic/)), so the subscription updating functionality in `GridMapVisualization` has been disabled for now.
- The parameters handled API in ROS2 is slightly different and so the parameters have been slightly modified, example:
From this:
```
grid_map_visualizations:
- name: elevation_points
type: point_cloud
params:
layer: elevation
- name: elevation_grid
type: occupancy_grid
params:
layer: elevation
data_min: 0.08
data_max: -0.16
```
To this:
```
grid_map_visualization:
ros__parameters:
grid_map_topic: /grid_map_simple_demo/grid_map
grid_map_visualizations: [elevation_points, elevation_grid]
elevation_points:
type: point_cloud …
```
=> [ros2] grid_map_visualization port

.circleci/config.yml, README.md, grid_map_ros/test/GridMapRosTest.cpp, tools/ros2_dependencies.repos
This fixes CI failure for ros2 branch.
Changes made:
* removed unnecessary dependencies in repos file (rcpputils, rosbag2, pcl_msgs can be installed by rosdep)
* fixed test failure in grid_map_ros package
=> Fix CI for ROS2

grid_map_sdf/CMakeLists.txt, grid_map_sdf/include/grid_map_sdf/SignedDistanceField.hpp, grid_map_sdf/package.xml, grid_map_sdf/src/SignedDistanceField.cpp
In https://github.com/ANYbotics/grid_map/issues/283 and https://github.com/ANYbotics/grid_map/issues/243, grid_map_sdf package was blocked due to pcl_ros binary not being released.
However, since grid_map_sdf only uses pure PCL library API, the dependency can be replaced with libpcl-all-dev
This PR fixes convertToPointCloud function to depend on PCL instead of pcl_ros.
This way, grid_map_ros does not have to wait for pcl_ros to be released as binary package every time new ROS distribution is released.
=> [ros2] fix convertToPointCloud function to use PCL instead of pcl_ros

.circleci/config.yml, grid_map_cmake_helpers/cmake/grid_map_package.cmake, grid_map_costmap_2d/test/test_costmap_2d_converter.cpp, grid_map_cv/package.xml, grid_map_demos/src/FiltersDemo.cpp, grid_map_demos/src/move_demo_node.cpp, grid_map_ros/src/GridMapRosConverter.cpp, grid_map_ros/src/PolygonRosConverter.cpp, grid_map_ros/test/GridMapRosTest.cpp, grid_map_visualization/src/GridMapVisualization.cpp, grid_map_visualization/src/visualizations/FlatPointCloudVisualization.cpp, grid_map_visualization/src/visualizations/GridCellsVisualization.cpp, grid_map_visualization/src/visualizations/MapRegionVisualization.cpp, grid_map_visualization/src/visualizations/OccupancyGridVisualization.cpp, grid_map_visualization/src/visualizations/PointCloudVisualization.cpp, grid_map_visualization/src/visualizations/VectorVisualization.cpp, tools/ros2_dependencies.repos
This PR contains
- https://github.com/ANYbotics/grid_map/pull/277 and rebase.
- Fix build error with rolling.
- Update for ci.
=> Update for rolliing

grid_map_cv/include/grid_map_cv/InpaintFilter.hpp, grid_map_demos/include/grid_map_demos/FiltersDemo.hpp, grid_map_demos/src/normal_filter_comparison_node.cpp, grid_map_filters/include/grid_map_filters/BufferNormalizerFilter.hpp, grid_map_filters/include/grid_map_filters/ColorBlendingFilter.hpp, grid_map_filters/include/grid_map_filters/ColorFillFilter.hpp, grid_map_filters/include/grid_map_filters/ColorMapFilter.hpp, grid_map_filters/include/grid_map_filters/CurvatureFilter.hpp, grid_map_filters/include/grid_map_filters/DeletionFilter.hpp, grid_map_filters/include/grid_map_filters/DuplicationFilter.hpp, grid_map_filters/include/grid_map_filters/LightIntensityFilter.hpp, grid_map_filters/include/grid_map_filters/MathExpressionFilter.hpp, grid_map_filters/include/grid_map_filters/MeanInRadiusFilter.hpp, grid_map_filters/include/grid_map_filters/MedianFillFilter.hpp, grid_map_filters/include/grid_map_filters/MinInRadiusFilter.hpp, grid_map_filters/include/grid_map_filters/MockFilter.hpp, grid_map_filters/include/grid_map_filters/NormalColorMapFilter.hpp, grid_map_filters/include/grid_map_filters/NormalVectorsFilter.hpp, grid_map_filters/include/grid_map_filters/SetBasicLayersFilter.hpp, grid_map_filters/include/grid_map_filters/SlidingWindowMathExpressionFilter.hpp, grid_map_filters/include/grid_map_filters/ThresholdFilter.hpp
This PR is melodic specific changed and re-opened from https://github.com/ANYbotics/grid_map/pull/298
**Problem Description**
For some reason, there seems to be a change in the header path extension. I am not sure if this is a change triggered from one of the dependencies, or if this package is working with a customized dependency somewhere. 
The build fails in the following systems
- Ubuntu 16.04 Xenial ROS Kinetic
- Ubuntu 18.04 Bionic ROS Melodic
- Ubuntu 20.04 Focal ROS Noetic
```
Errors     << grid_map_cv:make /home/jaeyoung/catkin_ws/logs/grid_map_cv/build.make.004.log                                                                                                                       
In file included from /home/jaeyoung/catkin_ws/src/grid_map/grid_map_cv/src/InpaintFilter.cpp:9:0: …
```
=> Switch header path from hpp to h

grid_map_pcl/include/grid_map_pcl/helpers.hpp, grid_map_pcl/src/helpers.cpp
- fix build problem when inline function is not defined in `*.hpp`.
I have the following build error when using `helpers.hpp` in `grid_map_pcl` at my project.
```
In file included from /home/hrkota/dev/autoware.proj/install/grid_map_pcl/include/grid_map_pcl/PointcloudProcessor.hpp:16,
from /home/hrkota/dev/autoware.proj/install/grid_map_pcl/include/grid_map_pcl/GridMapPclLoader.hpp:21,
from /home/hrkota/dev/autoware.proj/src/autoware/autoware.iv/map/map_loader/src/elevation_map_loader/elevation_map_loader_node.cpp:26:
/home/hrkota/dev/autoware.proj/install/grid_map_pcl/include/grid_map_pcl/helpers.hpp:44:13: error: inline function ‘void grid_map::grid_map_pcl::printTimeElapsedToRosInfoStream(const time_point&, const string&, const rclcpp::Logger&)’ used but never defined [-Werror]
44 | …
```
=> fix inline function for helpers in grid_map_pcl

.github/workflows/build_test.yml
**Problem Description**
This PR adds a build test CI for the `melodic-devel` branch, since the existing CI is not able to test this branch.
**Additional Context**
- Support for ROS melodic in this branch has been added through the branch `melodic-devel`
=> Add build tests for melodic-devel

grid_map_pcl/include/grid_map_pcl/helpers.hpp, grid_map_pcl/src/helpers.cpp
I have met following building error on Ubuntu-18.04(WSL2) with g++ version of 7.5.0.
1. Missing type declaration of `copyPointCloud` in `GridMapPclLoader.cpp` scope:
```
grid_map/grid_map_pcl/src/GridMapPclLoader.cpp: In member function ‘void grid_map::GridMapPclLoader::setRawInputCloud(pcl::PointCloud<pcl::PointXYZ>::ConstPtr)’:
grid_map/grid_map_pcl/src/GridMapPclLoader.cpp:62:8: error: ‘copyPointCloud’ is not a member of ‘pcl’
pcl::copyPointCloud(*rawInputCloud, *temp);
```
2. The compiler claims that a variable may be used uninitialized.
```
grid_map/grid_map_pcl/src/helpers.cpp:41:3: error: ‘isSetVerbosityLevelToDebug’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (!isSetVerbosityLevelToDebug) {
```
=> fixed building error with g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

grid_map_pcl/README.md, grid_map_pcl/config/parameters.yaml, grid_map_pcl/include/grid_map_pcl/PclLoaderParameters.hpp, grid_map_pcl/src/GridMapPclLoader.cpp, grid_map_pcl/src/PclLoaderParameters.cpp
Thank you for the work.
I added the method to  use the mean value of the cluster with the most points as elevation value.
This method may be able to estimate more ground-like values.
0: Smallest value among the average values ​​of each cluster (current method)
1: Mean value of the cluster with the most points (new method)
(height_thresh is a parameter for this methods to reduce the influence of point clouds that exist in high locations such as ceilings.)
=> Add height of cluster with the most points method

.circleci/config.yml, grid_map/package.xml, grid_map_core/CMakeLists.txt, grid_map_cv/CMakeLists.txt, grid_map_demos/CMakeLists.txt, grid_map_filters/CMakeLists.txt, grid_map_filters/src/ColorBlendingFilter.cpp, grid_map_loader/CMakeLists.txt, grid_map_octomap/CMakeLists.txt, grid_map_pcl/CMakeLists.txt, grid_map_pcl/src/GridMapPclLoader.cpp, grid_map_pcl/src/helpers.cpp, grid_map_ros/CMakeLists.txt, grid_map_rviz_plugin/CMakeLists.txt, grid_map_sdf/CMakeLists.txt, grid_map_visualization/CMakeLists.txt
fix build error as below on jammy
```
/usr/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h:24:102: error: ‘outputColor.Eigen::Array<float, 3, 1, 0, 3, 1>::<unnamed>.Eigen::PlainObjectBase<Eigen::Array<float, 3, 1, 0, 3, 1> >::m_storage.Eigen::DenseStorage<float, 3, 3, 1, 0>::m_data.Eigen::internal::plain_array<float, 3, 0, 0>::array[2]’ may be used uninitialized [-Werror=maybe-uninitialized]
24 |   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff(DstScalar& a, const SrcScalar& b) const { a = b; }
|                                                                                                    ~~^~~
/home/daisuke/workspace/sandbox_ws/src/grid_map/grid_map_filters/src/ColorBlendingFilter.cpp: In member function ‘bool grid_map::ColorBlendingFilter<T>::update(const T&, …
```
=> fix: build error on jammy

grid_map_core/CMakeLists.txt, grid_map_costmap_2d/CMakeLists.txt, grid_map_cv/CMakeLists.txt, grid_map_demos/CMakeLists.txt, grid_map_filters/CMakeLists.txt, grid_map_loader/CMakeLists.txt, grid_map_octomap/CMakeLists.txt, grid_map_pcl/CMakeLists.txt, grid_map_ros/CMakeLists.txt, grid_map_rviz_plugin/CMakeLists.txt, grid_map_sdf/CMakeLists.txt, grid_map_visualization/CMakeLists.txt
Allows it to build with ros2 humble on arm64 systems.
Makes compiler treat the Eigen as a system library, as it should.
Without the fix, we encounter following issues:
https://github.com/autowarefoundation/autoware/issues/357
Follow up from: https://github.com/tier4/grid_map/pull/2#pullrequestreview-983084399
=> fix: mark Eigen library as SYSTEM

grid_map_cv/include/grid_map_cv/GridMapCvConverter.hpp, grid_map_cv/include/grid_map_cv/GridMapCvProcessing.hpp, grid_map_cv/test/GridMapCvProcessingTest.cpp, grid_map_cv/test/GridMapCvTest.cpp, grid_map_demos/src/opencv_demo_node.cpp, grid_map_ros/include/grid_map_ros/GridMapRosConverter.hpp, grid_map_ros/test/GridMapRosTest.cpp
When compiling in rolling, an error of deprecated headers appears urging you to use the `cv_bridge.hpp` headers instead of 'cv_bridge.h'. This PR changes all of them, fixing these deprecation errors.
Signed-off-by: ivrolan <ivanlpzbrc01@gmail.com>
=> [ROS2 Rolling] changed cv_bridge.h -> .hpp

grid_map_cmake_helpers/cmake/grid_map_package.cmake, grid_map_demos/CMakeLists.txt, grid_map_filters/CMakeLists.txt
* Switch to CMAKE_CXX_COMPILER_ID
* https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html
* https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILER_IS_GNUCXX.html#cmake-compiler-is-gnucxx
=> Stop using deprecated CMAKE_COMPILER_IS_GNUCXX

grid_map_core/CMakeLists.txt, grid_map_cv/CMakeLists.txt
This fixes include errors in grid_map_geo ros2 port. If you need, I can rebase and target to rolling first.
Relates to #403, but to close that issue out, these changes should ideally be reflected across the whole repo.
=> grid_map_core: Use ament_export_targets and improve eigen linkage

.github/.mergify.yml
Add a Mergify CI file to help grid_map maintainers out with automatic features such as backporting. This reduces the time per pull-request needed to maintain multiple branches. Easier review and backport helps promote smaller PR's that are easier to review or revert. 
* For backport to iron and humble
* Asking to fix conflicts
* Deleting head branch after merge
1. Ask for a backport: https://github.com/Ryanf55/grid_map/pull/2#issuecomment-1925889673
2. Mergify replies that it created the backport: https://github.com/Ryanf55/grid_map/pull/2#issuecomment-1925889801
3. You can see it automatically creates the backport: https://github.com/Ryanf55/grid_map/pull/3
In the future, once we gain trust, I can add the automatic merge of backports as long as they pass CI. We should probably integrate …
=> ci(Mergify): Add initial config

grid_map_pcl/package.xml
Depend on PCL correctly. Dev versions are needed for dev, while runtime is only needed for runtime.
This is a rebased, and improved version of what's proposed in https://github.com/ANYbotics/grid_map/pull/341.
It adds a missing `build_export_depend` from what was suggested by @kazuki0824.
=> Split PCL deps for dev and runtime

grid_map/package.xml, grid_map_cmake_helpers/package.xml, grid_map_core/package.xml, grid_map_costmap_2d/package.xml, grid_map_cv/package.xml, grid_map_demos/package.xml, grid_map_filters/package.xml, grid_map_loader/package.xml, grid_map_msgs/package.xml, grid_map_octomap/package.xml, grid_map_pcl/package.xml, grid_map_ros/package.xml, grid_map_rviz_plugin/package.xml, grid_map_sdf/package.xml, grid_map_visualization/package.xml
Updating the list of maintainers to add myself and remove @SteveMacenski.
=> Add Ryan as maintainer, remove Steve

grid_map_cv/CMakeLists.txt
Use old-style CMake variables as a patch till this upstream issue makes it into humble binaries: https://github.com/ros/filters/pull/70
https://github.com/ANYbotics/grid_map/pull/404/files#diff-217de7f0d7eec88dce2cada8716bd30748cf9ad20d1211c56501a2acb56666bbL28
This PR forgot to add the include directories from `filters`, probably because there were no targets. I'm not sure how it builds on rolling and not humble. This patch can be replaced with a proper `target_link_libraries` call soon. 
It's blocking CI from passing in this PR: https://github.com/ANYbotics/grid_map/actions/runs/7943206475/job/21687293385?pr=440#step:6:25
```
$ cat /opt/ros/rolling/share/filters/cmake/ament_cmake_export_include_directories-extras.cmake 
set(_exported_include_dirs "${filters_DIR}/../../../include") …
```
=> Bugfix use old style include directories for filters

grid_map_costmap_2d/CMakeLists.txt, grid_map_costmap_2d/test/CMakeLists.txt
* Link to exported namespace targets when possible
* Use ament_export_libraries
* Relates to #403 
* https://github.com/ros-planning/navigation2/pull/4112
=> Use ament_export_targets in grid_map_costmap_2d

.github/workflows/colcon.yaml, grid_map_core/test/EigenPluginsTest.cpp, grid_map_cv/include/grid_map_cv/GridMapCvConverter.hpp, grid_map_filters/CMakeLists.txt, grid_map_ros/src/GridMapRosConverter.cpp, tools/ros2_dependencies.repos
- skip installing octomap server because it is still not available on rolling.
- ignore compiler warnings due to gcc 13 bug
=> build: treat several build issues on rolling 

grid_map_ros/test/GridMapRosTest.cpp
=> chore: replace deprecated rcpputils filesystem with std::filesystem

.github/workflows/colcon.yaml
The Jazzy image broke because rolling broke ABI. This should fix it. 
Each time we branch of `rolling`, we need to update the image. `rolling` will only work for a bit.
=> Use Jazzy image in CI instead of rolling

grid_map_demos/CMakeLists.txt, grid_map_octomap/package.xml
- closes #482  
- related to https://github.com/ros/rosdistro/issues/41622
=> build: switch to use system octomap

grid_map_core/src/iterators/SpiralIterator.cpp
Forward port of https://github.com/ANYbotics/grid_map/pull/479 to fix undefined behavior
=> Fix UB in SpiralIterator::operator++

grid_map_ros/package.xml
Fix issue in CI with rosbag throwing exception in the CI test environment because it fails to initialize from missing the sqlite plugin
None, this is build farm only. in order to reproduce this, I have set up a new CI job in #492. 
I then rebased 492 on top of this PR, and will see if it's resolved.
Closes #490
=> Add test dependency to on rosbag default plugins

.github/workflows/industrial-ci.yaml
Add the ROS industrial CI which supposedly can help find missing dependencies earlier in a more minimal test environment.
We currently use `rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-desktop-latest` as an image, which contains all dependencies. 
If we forget dependencies in the package.xml, our CI passes, but the jenkins CI fails.
From what I have read, [ros-industrial](https://github.com/ros-industrial/industrial_ci?tab=readme-ov-file#for-github-actions) can solve that.
Let's see if this can reproduce any test failures we have on the jenkins build farm.
=> Add industrial CI
